export type SeedProduct = {
  slug: string;
  name: string;
  brand: string;
  category: string;
  ingredientIds: string[];
  fullIngredients: string;
  origin: string;
  description: string;
  usageSteps: string[];
  officialUrl?: string;
  price: number;
  currency: string;
  skinTypes: string[];
  concerns: string[];
  featured?: boolean;
};

// Researched product data — real products, real actives, real brand HQ.
// imageUrl intentionally omitted: no verified official image URLs were
// confirmed during research, and hotlinking a guessed CDN path is not
// acceptable. Add real photos via the admin once you have licensed/
// official assets.
export const PRODUCTS: SeedProduct[] = [
  {
    slug: "cosrx-low-ph-good-morning-gel-cleanser",
    name: "Low pH Good Morning Gel Cleanser",
    brand: "COSRX",
    category: "cleanser",
    ingredientIds: [],
    fullIngredients:
      "Tea tree leaf oil, betaine salicylate, cocamidopropyl betaine, low-pH surfactant base",
    origin: "South Korea",
    description:
      "A low-pH gel cleanser built around tea tree oil and a trace of BHA, designed to clean without stripping the skin barrier — a K-beauty staple for the first AM step.",
    usageSteps: [
      "Massage a small amount onto damp skin",
      "Work into a light lather",
      "Rinse off with lukewarm water",
    ],
    officialUrl: "https://cosrx.com",
    price: 13,
    currency: "USD",
    skinTypes: ["oily", "combination", "normal", "sensitive"],
    concerns: ["acne", "barrier"],
    featured: true,
  },
  {
    slug: "cosrx-advanced-snail-96-mucin-power-essence",
    name: "Advanced Snail 96 Mucin Power Essence",
    brand: "COSRX",
    category: "essence",
    ingredientIds: ["hyaluronic_acid"],
    fullIngredients:
      "Snail secretion filtrate 96.3%, sodium hyaluronate, panthenol, allantoin, arginine, betaine",
    origin: "South Korea",
    description:
      "COSRX's signature snail mucin essence — hydrating, barrier-supportive, and one of the most reviewed K-beauty products worldwide.",
    usageSteps: [
      "Apply after toner/first essence",
      "Pat or press 2-3 drops onto face and neck",
      "Leave on, no rinse — follow with moisturizer",
    ],
    officialUrl: "https://cosrx.com",
    price: 18,
    currency: "USD",
    skinTypes: ["oily", "dry", "combination", "normal", "sensitive"],
    concerns: ["hydration", "redness", "dullness"],
    featured: true,
  },
  {
    slug: "round-lab-vita-niacinamide-dark-spot-serum",
    name: "Vita Niacinamide Dark Spot Serum",
    brand: "Round Lab",
    category: "serum",
    ingredientIds: ["niacinamide", "vitamin_c"],
    fullIngredients:
      "Niacinamide, 3-O-ethyl ascorbic acid (stabilized vitamin C), seaberry (Hippophae rhamnoides) water/extract",
    origin: "South Korea",
    description:
      "Pairs niacinamide with a stabilized vitamin C derivative to fade dark spots and even tone without the instability of pure L-ascorbic acid.",
    usageSteps: [
      "Apply after toner",
      "Pat a few drops onto face",
      "Follow with moisturizer/SPF — best used AM given the vitamin C",
    ],
    officialUrl: "https://roundlab.com",
    price: 20,
    currency: "USD",
    skinTypes: ["normal", "combination"],
    concerns: ["pigmentation", "dullness"],
    featured: true,
  },
  {
    slug: "some-by-mi-retinol-intense-reactivating-serum",
    name: "Retinol Intense Reactivating Serum",
    brand: "Some By Mi",
    category: "serum",
    ingredientIds: ["retinol", "niacinamide"],
    fullIngredients: "Retinal, retinol, bakuchiol, niacinamide, panthenol",
    origin: "South Korea",
    description:
      "A retinal/retinol blend reinforced with bakuchiol (a gentler retinol alternative) for cell turnover and fine lines — a strong evening active, not a beginner product.",
    usageSteps: [
      "PM only — start 2-3x/week to build tolerance",
      "Apply a few drops to clean, dry skin as the last step before moisturizer",
      "Avoid the eye area; always follow with SPF the next morning",
    ],
    price: 20,
    currency: "USD",
    skinTypes: ["normal", "combination"],
    concerns: ["aging", "pores"],
    featured: true,
  },
  {
    slug: "cosrx-bha-blackhead-power-liquid",
    name: "BHA Blackhead Power Liquid",
    brand: "COSRX",
    category: "toner",
    ingredientIds: ["bha", "niacinamide"],
    fullIngredients: "Betaine salicylate 4% (BHA), niacinamide, willow bark water, panthenol",
    origin: "South Korea",
    description:
      "A cult-favorite BHA toner that unclogs pores and smooths texture — start every other day to build tolerance.",
    usageSteps: [
      "Apply after cleansing with a cotton pad or hands",
      "Pat in, leave on",
      "Follow with moisturizer",
    ],
    officialUrl: "https://cosrx.com",
    price: 17,
    currency: "USD",
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "pores"],
    featured: true,
  },
  {
    slug: "beauty-of-joseon-green-plum-refreshing-toner",
    name: "Green Plum Refreshing Toner: AHA + BHA",
    brand: "Beauty of Joseon",
    category: "toner",
    ingredientIds: ["aha", "bha"],
    fullIngredients:
      "Glycolic acid 2%, salicylic acid 0.5%, green plum water 25%, mung bean extract 2%",
    origin: "South Korea",
    description:
      "A gentle daily-use AHA/BHA toner — low enough concentration for regular use, but still a real exfoliant to factor into your routine.",
    usageSteps: [
      "Apply after cleansing",
      "Sweep with a cotton pad or pat with hands",
      "Leave on, follow with essence/moisturizer",
    ],
    officialUrl: "https://beautyofjoseon.com",
    price: 17,
    currency: "USD",
    skinTypes: ["oily", "combination", "normal", "sensitive"],
    concerns: ["dullness", "pores", "pigmentation"],
    featured: true,
  },
  {
    slug: "beauty-of-joseon-dynasty-cream",
    name: "Dynasty Cream",
    brand: "Beauty of Joseon",
    category: "moisturizer",
    ingredientIds: ["niacinamide"],
    fullIngredients: "Rice bran water, ginseng root water, squalane, niacinamide, glycerin",
    origin: "South Korea",
    description:
      "A rich, ginseng-forward moisturizer for barrier repair and a dewy glow — the final leave-on layer of the routine.",
    usageSteps: [
      "Scoop a pea-to-nickel-size amount",
      "Massage in as the final leave-on layer (before sunscreen in AM)",
    ],
    officialUrl: "https://beautyofjoseon.com",
    price: 21,
    currency: "USD",
    skinTypes: ["dry", "normal"],
    concerns: ["hydration", "barrier"],
    featured: true,
  },
  {
    slug: "beauty-of-joseon-relief-sun",
    name: "Relief Sun: Rice + Probiotics SPF50+ PA++++",
    brand: "Beauty of Joseon",
    category: "sunscreen",
    ingredientIds: ["spf", "niacinamide"],
    fullIngredients:
      "Rice extract 30%, niacinamide, ginseng root extract, green tea extract, probiotic ferment complex, chemical UV filters",
    origin: "South Korea",
    description:
      "The best-selling K-beauty sunscreen — a genuinely comfortable, non-greasy SPF50+ that doubles as the final step of a morning routine.",
    usageSteps: [
      "Apply as the last AM step",
      "Use about two finger-lengths, generously",
      "Reapply every 2 hours during sun exposure",
    ],
    officialUrl: "https://beautyofjoseon.com",
    price: 18,
    currency: "USD",
    skinTypes: ["oily", "dry", "combination", "normal", "sensitive"],
    concerns: ["hydration", "dullness"],
    featured: true,
  },
  {
    slug: "la-roche-posay-effaclar-duo",
    name: "Effaclar Duo(+) Dual Action Acne Spot Treatment",
    brand: "La Roche-Posay",
    category: "spot",
    ingredientIds: ["benzoyl_peroxide", "niacinamide"],
    fullIngredients: "Micronized benzoyl peroxide 5.5%, lipo-hydroxy acid (LHA), niacinamide",
    origin: "France",
    description:
      "A dermatologist staple: micronized, lower-irritation benzoyl peroxide for acne spot treatment, from one of the largest pharmacy skincare brands.",
    usageSteps: [
      "Apply after cleansing/toning",
      "Apply a thin layer to blemishes or affected areas, 1-2x/day",
      "Leave on — do not rinse",
    ],
    officialUrl: "https://www.laroche-posay.us",
    price: 35,
    currency: "USD",
    skinTypes: ["oily", "combination"],
    concerns: ["acne"],
    featured: true,
  },
  {
    slug: "klairs-freshly-juiced-vitamin-drop",
    name: "Freshly Juiced Vitamin Drop",
    brand: "Dear, Klairs",
    category: "serum",
    ingredientIds: ["vitamin_c"],
    fullIngredients:
      "Ascorbic acid (pure vitamin C) 5%, centella asiatica extract, citrus/anise/broccoli botanical extracts",
    origin: "South Korea",
    description:
      "A low-strength, sensitive-skin-friendly pure vitamin C serum — a gentler entry point than high-percentage L-ascorbic acid formulas.",
    usageSteps: [
      "Apply after toner, AM or PM",
      "Apply a few drops evenly, pat in",
      "Follow with moisturizer/SPF",
    ],
    officialUrl: "https://klairs.com",
    price: 22,
    currency: "USD",
    skinTypes: ["sensitive", "normal", "dry", "combination", "oily"],
    concerns: ["dullness", "pigmentation"],
  },
  {
    slug: "the-ordinary-niacinamide-10-zinc-1",
    name: "Niacinamide 10% + Zinc 1%",
    brand: "The Ordinary",
    category: "serum",
    ingredientIds: ["niacinamide"],
    fullIngredients: "Niacinamide 10%, zinc PCA 1%",
    origin: "Canada",
    description:
      "The product that made niacinamide mainstream — high concentration, budget price, targets oil and enlarged pores.",
    usageSteps: [
      "Apply after cleansing/toning, AM and/or PM",
      "Apply a few drops to face",
      "Avoid layering directly under pure vitamin C — space them out",
    ],
    officialUrl: "https://theordinary.com",
    price: 10,
    currency: "USD",
    skinTypes: ["oily", "combination"],
    concerns: ["pores", "acne", "dullness"],
  },
  {
    slug: "dr-jart-cicapair-color-correcting-treatment",
    name: "Cicapair Tiger Grass Color Correcting Treatment SPF30",
    brand: "Dr. Jart+",
    category: "sunscreen",
    ingredientIds: ["niacinamide", "centella", "spf"],
    fullIngredients:
      "Madecassoside, centella asiatica extract, niacinamide, titanium dioxide/zinc oxide",
    origin: "South Korea",
    description:
      "A green-to-beige color-correcting SPF that calms redness while protecting from UV — a 3-in-1 moisturizer/primer/sunscreen for reactive skin.",
    usageSteps: [
      "Last AM step",
      "Apply evenly over the face — the green tint neutralizes redness as it sets",
      "Leave on as the final layer",
    ],
    officialUrl: "https://drjart.com",
    price: 50,
    currency: "USD",
    skinTypes: ["sensitive", "normal", "combination"],
    concerns: ["redness", "pigmentation"],
  },
  {
    slug: "torriden-dive-in-hyaluronic-acid-serum",
    name: "DIVE-IN Low Molecule Hyaluronic Acid Serum",
    brand: "Torriden",
    category: "serum",
    ingredientIds: ["hyaluronic_acid", "centella"],
    fullIngredients:
      "5 types of hyaluronic acid, panthenol, allantoin, madecassoside, beta-glucan",
    origin: "South Korea",
    description:
      "Five molecular weights of hyaluronic acid for hydration at every skin depth — a lightweight, dedicated hydration serum.",
    usageSteps: [
      "Apply after toner, AM & PM",
      "Pat/press a few drops in",
      "Follow immediately with moisturizer to seal in hydration",
    ],
    price: 19,
    currency: "USD",
    skinTypes: ["dry", "sensitive", "normal", "combination", "oily"],
    concerns: ["hydration", "dullness"],
  },
  {
    slug: "tosowoong-copper-peptide-face-serum",
    name: "Copper Peptide Face Serum",
    brand: "TOSOWOONG",
    category: "serum",
    ingredientIds: ["peptides"],
    fullIngredients:
      "Copper tripeptide-1 (GHK-Cu), multi-peptide complex (11+ peptides incl. acetyl hexapeptide-8)",
    origin: "South Korea",
    description:
      "A dedicated copper-peptide serum for firmness and barrier repair — pairs poorly with acidic exfoliants (apply at a different time).",
    usageSteps: [
      "Apply after toner, AM or PM",
      "Apply a few drops, pat in",
      "Follow with moisturizer",
    ],
    price: 21,
    currency: "USD",
    skinTypes: ["normal", "dry", "combination"],
    concerns: ["aging", "barrier"],
  },
  {
    slug: "isntree-tw-real-eye-cream",
    name: "TW-Real Eye Cream",
    brand: "ISNTREE",
    category: "eye",
    ingredientIds: ["niacinamide", "ceramides"],
    fullIngredients:
      "Adenosine, 4 peptides, 61% bifida ferment lysate, ceramide, niacinamide",
    origin: "South Korea",
    description:
      "A peptide-and-ceramide eye cream for fine lines and puffiness, gentle enough for the delicate orbital area.",
    usageSteps: [
      "Last step, AM & PM",
      "Dot a small amount around the orbital bone with your ring finger",
      "Gently pat/tap in — avoid direct contact with the eyes",
    ],
    price: 18,
    currency: "USD",
    skinTypes: ["normal", "dry"],
    concerns: ["aging"],
  },
  {
    slug: "isntree-hyaluronic-acid-watery-sun-gel",
    name: "Hyaluronic Acid Watery Sun Gel SPF50+ PA++++",
    brand: "ISNTREE",
    category: "sunscreen",
    ingredientIds: ["hyaluronic_acid", "niacinamide", "centella", "spf"],
    fullIngredients: "Niacinamide, multiple hyaluronic acid types, centella asiatica extract",
    origin: "South Korea",
    description:
      "A watery, hydrating sunscreen with hyaluronic acid and centella baked in — a favorite for dehydrated or combination skin.",
    usageSteps: ["Last AM step", "Apply generously as the final layer", "Reapply every 2 hours in the sun"],
    price: 19,
    currency: "USD",
    skinTypes: ["oily", "dry", "combination", "normal"],
    concerns: ["hydration"],
  },
  {
    slug: "medicube-zero-pore-pad-2",
    name: "Zero Pore Pad 2.0",
    brand: "Medicube",
    category: "toner",
    ingredientIds: ["bha", "aha"],
    fullIngredients: "Salicylic acid (BHA), lactic acid (AHA), panthenol, allantoin",
    origin: "South Korea",
    description:
      "Textured exfoliating toner pads for pore care — one side textured for gentle physical buffing, the other smooth for product application.",
    usageSteps: [
      "After cleansing, wipe the textured side over the face",
      "Follow with the smooth side",
      "Leave on, continue with the rest of your routine",
    ],
    officialUrl: "https://medicube.us",
    price: 26,
    currency: "USD",
    skinTypes: ["oily", "combination"],
    concerns: ["pores", "acne"],
  },
  {
    slug: "medicube-deep-vita-a-retinol-serum",
    name: "Deep Vita A Retinol Serum",
    brand: "Medicube",
    category: "serum",
    ingredientIds: ["retinol"],
    fullIngredients: "Hydroxypinacolone retinoate (HPR, 4th-gen retinoid ester), soothing complex",
    origin: "South Korea",
    description:
      "Uses HPR, a gentler retinoid ester, instead of classic retinol — aims for similar results with less irritation.",
    usageSteps: [
      "PM step, as the last layer before moisturizer",
      "Apply a few drops",
      "Always follow with SPF the next morning",
    ],
    officialUrl: "https://medicube.us",
    price: 34,
    currency: "USD",
    skinTypes: ["normal", "combination"],
    concerns: ["aging"],
  },
  {
    slug: "anua-heartleaf-77-soothing-toner",
    name: "Heartleaf 77% Soothing Toner",
    brand: "Anua",
    category: "toner",
    ingredientIds: ["centella"],
    fullIngredients: "Houttuynia cordata (heartleaf) extract 77%, panthenol, centella asiatica extract",
    origin: "South Korea",
    description:
      "Anua's breakout product — a heartleaf-forward calming toner that can be layered 2-3x for redness-prone or oily, irritated skin.",
    usageSteps: [
      "After cleansing",
      "Sweep with a cotton pad or pat with hands, layer 2-3x if desired",
      "Leave on, follow with serum/moisturizer",
    ],
    officialUrl: "https://anua.com",
    price: 18,
    currency: "USD",
    skinTypes: ["sensitive", "oily", "combination"],
    concerns: ["redness", "acne"],
  },
  {
    slug: "aestura-atobarrier-365-cream",
    name: "ATOBARRIER365 Cream",
    brand: "Aestura",
    category: "moisturizer",
    ingredientIds: ["ceramides", "niacinamide"],
    fullIngredients: "High-density ceramide capsules, niacinamide, phytosphingosine, squalane",
    origin: "South Korea",
    description:
      "A dermocosmetic barrier-repair cream built around ceramide capsules — developed with a compromised-barrier/atopic-skin focus.",
    usageSteps: ["Last leave-on layer, AM/PM", "Apply generously over face and neck", "Massage in"],
    price: 24,
    currency: "USD",
    skinTypes: ["dry", "sensitive"],
    concerns: ["barrier", "redness", "hydration"],
  },
  {
    slug: "purito-wonder-releaf-centella-serum-unscented",
    name: "Wonder Releaf Centella Serum (Unscented)",
    brand: "PURITO SEOUL",
    category: "serum",
    ingredientIds: ["centella", "niacinamide", "peptides", "ceramides"],
    fullIngredients:
      "Centella asiatica extract 34,860ppm, niacinamide, 4 peptides, ceramide NP",
    origin: "South Korea",
    description:
      "A high-concentration centella serum in a fragrance-free formula, aimed squarely at redness and barrier repair for reactive skin.",
    usageSteps: ["Apply after toner", "Apply a few drops, pat in", "Follow with moisturizer"],
    officialUrl: "https://purito.com",
    price: 21,
    currency: "USD",
    skinTypes: ["sensitive", "normal", "dry", "combination", "oily"],
    concerns: ["redness", "barrier"],
  },
  {
    slug: "purito-plainet-squalane-oil-100",
    name: "Plainet Squalane Oil 100",
    brand: "PURITO SEOUL",
    category: "oil",
    ingredientIds: [],
    fullIngredients: "100% squalane (sugarcane-derived)",
    origin: "South Korea",
    description:
      "A single-ingredient squalane oil — an occlusive final step or a booster mixed into moisturizer/foundation.",
    usageSteps: [
      "Final AM/PM step, or mix into moisturizer",
      "Press 2-3 drops onto the face",
      "Can be layered over moisturizer to seal in hydration",
    ],
    officialUrl: "https://purito.com",
    price: 16,
    currency: "USD",
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["hydration", "dullness"],
  },
  {
    slug: "cerave-hydrating-facial-cleanser",
    name: "Hydrating Facial Cleanser",
    brand: "CeraVe",
    category: "cleanser",
    ingredientIds: ["ceramides", "hyaluronic_acid"],
    fullIngredients: "Ceramides (NP, AP, EOP), hyaluronic acid, glycerin, MVE delivery technology",
    origin: "USA",
    description: "A non-foaming, dermatologist-developed cleanser that pairs three essential ceramides with hyaluronic acid to remove dirt and makeup without disrupting the skin barrier — a dermatology staple for normal-to-dry and sensitive skin.",
    usageSteps: [
      "Wet face with lukewarm water",
      "Massage gently over face, avoiding harsh rubbing",
      "Rinse thoroughly and pat dry",
    ],
    officialUrl: "https://www.cerave.com",
    price: 14,
    currency: "USD",
    skinTypes: ["dry", "sensitive", "normal"],
    concerns: ["hydration", "barrier"],
  },
  {
    slug: "banila-co-clean-it-zero-cleansing-balm-original",
    name: "Clean It Zero Cleansing Balm Original",
    brand: "Banila Co",
    category: "cleanser",
    ingredientIds: ["vitamin_e"],
    fullIngredients: "Hot springs water, tocopheryl acetate (vitamin E), acerola fruit extract, botanical ester oil blend",
    origin: "South Korea",
    description: "The original balm-to-oil cleanser that popularized double cleansing in K-beauty — melts away makeup and sunscreen without stripping skin, then emulsifies into a milky texture on contact with water.",
    usageSteps: [
      "Scoop a small amount with dry hands onto dry skin",
      "Massage over face to dissolve makeup/sunscreen",
      "Add water to emulsify, then rinse off",
    ],
    officialUrl: "https://banilausa.com",
    price: 21,
    currency: "USD",
    skinTypes: ["oily", "dry", "combination", "normal"],
    concerns: ["dullness"],
  },
  {
    slug: "cosrx-advanced-snail-peptide-eye-cream",
    name: "Advanced Snail Peptide Eye Cream",
    brand: "COSRX",
    category: "eye",
    ingredientIds: ["hyaluronic_acid", "niacinamide", "peptides"],
    fullIngredients: "Snail secretion filtrate 73.7%, niacinamide 2%, 5-peptide complex, adenosine, sodium hyaluronate",
    origin: "South Korea",
    description: "Combines COSRX's signature snail mucin with a five-peptide complex and niacinamide to target dark circles, puffiness, and fine lines around the eye area.",
    usageSteps: [
      "Last step, AM & PM",
      "Dot a small amount around the orbital bone",
      "Gently pat in with ring finger until absorbed",
    ],
    officialUrl: "https://www.cosrx.com",
    price: 28,
    currency: "USD",
    skinTypes: ["normal", "dry", "combination"],
    concerns: ["aging", "hydration"],
  },
  {
    slug: "cerave-eye-repair-cream",
    name: "Eye Repair Cream",
    brand: "CeraVe",
    category: "eye",
    ingredientIds: ["ceramides", "hyaluronic_acid", "niacinamide"],
    fullIngredients: "Three essential ceramides, hyaluronic acid, niacinamide, marine & botanical complex",
    origin: "USA",
    description: "An oil-free, fragrance-free eye cream developed with dermatologists to reduce the look of dark circles and puffiness while reinforcing the skin barrier around the delicate eye area.",
    usageSteps: [
      "Apply AM and/or PM",
      "Dot gently around the orbital bone",
      "Pat in until fully absorbed — avoid direct contact with eyes",
    ],
    officialUrl: "https://www.cerave.com",
    price: 17,
    currency: "USD",
    skinTypes: ["normal", "dry", "sensitive", "combination"],
    concerns: ["aging", "hydration"],
  },
  {
    slug: "the-ordinary-100-organic-cold-pressed-rose-hip-seed-oil",
    name: "100% Organic Cold-Pressed Rose Hip Seed Oil",
    brand: "The Ordinary",
    category: "oil",
    ingredientIds: [],
    fullIngredients: "100% organic, cold-pressed rosehip seed oil (Rosa canina), naturally rich in linoleic and linolenic essential fatty acids",
    origin: "Canada",
    description: "A single-ingredient, unrefined rosehip seed oil marketed to help address signs of aging and uneven skin tone through its naturally high essential fatty acid content.",
    usageSteps: [
      "Apply as the final step, AM or PM",
      "Press 2-3 drops between palms and press onto face",
      "Can be mixed into moisturizer for extra nourishment",
    ],
    officialUrl: "https://theordinary.com",
    price: 10,
    currency: "USD",
    skinTypes: ["dry", "normal", "combination"],
    concerns: ["aging", "dullness"],
  },
  {
    slug: "sulwhasoo-concentrated-ginseng-renewing-facial-oil",
    name: "Concentrated Ginseng Renewing Facial Oil",
    brand: "Sulwhasoo",
    category: "oil",
    ingredientIds: [],
    fullIngredients: "Panax ginseng seed oil, camellia japonica seed oil, sesame seed oil",
    origin: "South Korea",
    description: "A luxury facial oil cold-pressed from ginseng seeds and blended with camellia and sesame oils, from the heritage Korean beauty house Sulwhasoo, aimed at nourishing and revitalizing dull, tired-looking skin.",
    usageSteps: [
      "Final PM step after moisturizer",
      "Warm 2-3 drops between palms",
      "Press gently over face and neck",
    ],
    officialUrl: "https://us.sulwhasoo.com",
    price: 84,
    currency: "USD",
    skinTypes: ["dry", "normal"],
    concerns: ["aging", "dullness", "hydration"],
  },
  {
    slug: "cosrx-acne-pimple-master-patch",
    name: "Acne Pimple Master Patch",
    brand: "COSRX",
    category: "spot",
    ingredientIds: [],
    fullIngredients: "Hydrocolloid patch (polyurethane film with absorbent hydrocolloid layer) — no topical actives",
    origin: "South Korea",
    description: "A best-selling hydrocolloid patch that absorbs fluid from popped or oozing blemishes and shields them from picking and bacteria — one of the most recognizable spot products in K-beauty.",
    usageSteps: [
      "Apply to clean, dry skin over a blemish",
      "Choose the dot size that fully covers the spot",
      "Leave on until it turns white/cloudy, then replace",
    ],
    officialUrl: "https://www.cosrx.com",
    price: 6,
    currency: "USD",
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["acne"],
  },
  {
    slug: "mario-badescu-drying-lotion",
    name: "Drying Lotion",
    brand: "Mario Badescu",
    category: "spot",
    ingredientIds: ["bha"],
    fullIngredients: "Salicylic acid, calamine, sulfur, camphor, zinc oxide",
    origin: "USA",
    description: "A cult-favorite overnight spot treatment: a settled layer of calamine and salicylic acid — you dab only the pink sediment from the bottom of the bottle directly onto blemishes to dry them out overnight.",
    usageSteps: [
      "Let the bottle settle, then dip a cotton swab into the pink sediment at the bottom",
      "Dab directly onto blemishes before bed",
      "Leave on overnight, rinse off in the morning",
    ],
    officialUrl: "https://www.mariobadescu.com",
    price: 17,
    currency: "USD",
    skinTypes: ["oily", "combination"],
    concerns: ["acne"],
  },
  {
    slug: "missha-time-revolution-first-treatment-essence",
    name: "Time Revolution The First Treatment Essence 5X",
    brand: "MISSHA",
    category: "essence",
    ingredientIds: ["niacinamide", "ceramides"],
    fullIngredients: "97% Desert Cica (yeast) ferment filtrate, niacinamide, ceramide NP, adenosine, bifida ferment lysate",
    origin: "South Korea",
    description: "MISSHA's iconic fermented 'first essence,' built around a high concentration of yeast ferment filtrate to prep skin, even tone, and support the moisture barrier before the rest of the routine.",
    usageSteps: [
      "Apply after toner, AM & PM",
      "Pat 2-3 drops onto face and neck",
      "Follow with serum/moisturizer",
    ],
    officialUrl: "https://misshaus.com",
    price: 43,
    currency: "USD",
    skinTypes: ["normal", "dry", "combination", "sensitive"],
    concerns: ["dullness", "aging", "hydration"],
  },
  {
    slug: "sk-ii-facial-treatment-essence",
    name: "Facial Treatment Essence",
    brand: "SK-II",
    category: "essence",
    ingredientIds: [],
    fullIngredients: "90%+ PITERA (Galactomyces ferment filtrate)",
    origin: "Japan",
    description: "SK-II's iconic essence built on PITERA, a proprietary fermentation ingredient first identified from sake brewers' hands — used to improve the look of skin texture, tone, and resilience.",
    usageSteps: [
      "Apply after cleansing, AM & PM",
      "Sweep onto a cotton pad or pat directly into skin",
      "Follow with serum/moisturizer",
    ],
    officialUrl: "https://www.sk-ii.com",
    price: 99,
    currency: "USD",
    skinTypes: ["normal", "dry", "combination", "oily"],
    concerns: ["aging", "dullness", "hydration"],
  },
  {
    slug: "illiyoon-ceramide-ato-concentrate-cream",
    name: "Ceramide Ato Concentrate Cream",
    brand: "ILLIYOON",
    category: "moisturizer",
    ingredientIds: ["ceramides"],
    fullIngredients: "Ceramide Ato Complex (3 ceramide types), panax ginseng root water, cholesterol, phytosphingosine",
    origin: "South Korea",
    description: "A fragrance-free, barrier-repair cream built around Illiyoon's 3-ceramide 'Ato Complex' — popular for very dry, sensitive, and eczema-prone skin on both face and body.",
    usageSteps: [
      "Apply to face and/or body after cleansing",
      "Massage in until absorbed",
      "Use daily, AM and/or PM",
    ],
    officialUrl: "https://theilliyoon.com",
    price: 24,
    currency: "USD",
    skinTypes: ["dry", "sensitive", "normal"],
    concerns: ["barrier", "hydration", "redness"],
  },
  {
    slug: "pyunkang-yul-essence-toner",
    name: "Essence Toner",
    brand: "Pyunkang Yul",
    category: "toner",
    ingredientIds: [],
    fullIngredients: "91% astragalus membranaceus root extract, minimal-ingredient alcohol-free base",
    origin: "South Korea",
    description: "A minimalist, astragalus-root-based toner from Pyunkang Yul, a brand developed with a Korean oriental medicine clinic focused on sensitive and atopic-prone skin — designed to hydrate and rebuild the barrier with as few ingredients as possible.",
    usageSteps: [
      "Apply after cleansing",
      "Pat or sweep onto face with hands or a cotton pad",
      "Follow with serum/moisturizer",
    ],
    officialUrl: "https://pyunkangyul.us",
    price: 17,
    currency: "USD",
    skinTypes: ["sensitive", "dry", "normal", "combination"],
    concerns: ["hydration", "barrier", "redness"],
  },
  {
    slug: "etude-house-soonjung-ph-6-5-whip-cleanser",
    name: "SoonJung pH 6.5 Whip Cleanser",
    brand: "Etude House",
    category: "cleanser",
    ingredientIds: ["centella"],
    fullIngredients: "Panthenol, madecassoside (a centella asiatica derivative), camellia sinensis leaf extract, low-pH (6.5) surfactant base",
    origin: "South Korea",
    description: "A low-pH, fragrance-free whip cleanser built around madecassoside and panthenol to clean sensitive, redness-prone skin without disrupting the barrier.",
    usageSteps: [
      "Pump onto damp hands or a cleansing puff",
      "Work into a soft foam and massage over face",
      "Rinse with lukewarm water",
    ],
    officialUrl: "https://www.etudehouse.com",
    price: 15,
    currency: "USD",
    skinTypes: ["sensitive", "dry", "normal", "combination"],
    concerns: ["redness", "barrier"],
  },
  {
    slug: "abib-heartleaf-acne-foam-cleanser",
    name: "Heartleaf Acne Foam Cleanser (Heartleaf Foam)",
    brand: "Abib",
    category: "cleanser",
    ingredientIds: ["bha", "centella"],
    fullIngredients: "Salicylic acid, Houttuynia cordata (heartleaf) extract, centella asiatica extract, panthenol",
    origin: "South Korea",
    description: "A mildly acidic foaming cleanser with salicylic acid and heartleaf extract that clears pores and calms redness for acne-prone, sensitive skin.",
    usageSteps: [
      "Lather with water",
      "Massage gently over face",
      "Rinse thoroughly",
    ],
    officialUrl: "https://en.abib.com",
    price: 15,
    currency: "USD",
    skinTypes: ["oily", "combination", "sensitive"],
    concerns: ["acne", "redness", "pores"],
  },
  {
    slug: "youth-to-the-people-superfood-antioxidant-cleanser",
    name: "Superfood Antioxidant Cleanser (Kale + Green Tea)",
    brand: "Youth To The People",
    category: "cleanser",
    ingredientIds: ["vitamin_c", "vitamin_e"],
    fullIngredients: "Kale, spinach, green tea, and alfalfa antioxidant blend, tetrahexyldecyl ascorbate (vitamin C), tocopheryl acetate (vitamin E), panthenol",
    origin: "USA",
    description: "A sulfate-free gel cleanser packed with kale, spinach, and green tea antioxidants that removes makeup and daily grime without stripping the skin barrier.",
    usageSteps: [
      "Massage onto damp skin",
      "Work into a gentle lather",
      "Rinse with lukewarm water",
    ],
    officialUrl: "https://www.youthtothepeople.com",
    price: 36,
    currency: "USD",
    skinTypes: ["oily", "dry", "combination", "normal", "sensitive"],
    concerns: ["dullness"],
  },
  {
    slug: "skin1004-madagascar-centella-toning-toner",
    name: "Madagascar Centella Toning Toner",
    brand: "SKIN1004",
    category: "toner",
    ingredientIds: ["centella", "niacinamide", "hyaluronic_acid"],
    fullIngredients: "84% centella asiatica extract, niacinamide, gluconolactone (PHA), hyaluronic acid, adenosine",
    origin: "South Korea",
    description: "A daily gentle-exfoliating toner combining a high concentration of centella asiatica with PHA and niacinamide to hydrate, soothe, and smooth texture.",
    usageSteps: [
      "Apply after cleansing with a cotton pad or hands",
      "Pat or sweep over face",
      "Follow with essence/serum",
    ],
    officialUrl: "https://www.skin1004.com",
    price: 19,
    currency: "USD",
    skinTypes: ["oily", "dry", "combination", "normal", "sensitive"],
    concerns: ["hydration", "dullness", "pores"],
  },
  {
    slug: "by-wishtrend-mandelic-acid-5-skin-prep-water",
    name: "Mandelic Acid 5% Skin Prep Water",
    brand: "By Wishtrend",
    category: "toner",
    ingredientIds: ["aha", "hyaluronic_acid", "centella"],
    fullIngredients: "Mandelic acid 5%, beta-glucan, panthenol, centella asiatica extract, sodium hyaluronate",
    origin: "South Korea",
    description: "A gentle exfoliating toner using mandelic acid, a larger-molecule AHA that's less irritating than glycolic acid, to smooth texture and fade dark spots while beta-glucan and centella soothe.",
    usageSteps: [
      "Apply after cleansing with a cotton pad",
      "Sweep over face, avoiding the eye area",
      "Follow with serum/moisturizer — start 2-3x/week to build tolerance",
    ],
    officialUrl: "https://www.wishtrend.com",
    price: 22,
    currency: "USD",
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["pores", "pigmentation", "dullness"],
  },
  {
    slug: "haruharu-wonder-black-rice-hyaluronic-toner",
    name: "Black Rice Hyaluronic Toner",
    brand: "Haruharu Wonder",
    category: "toner",
    ingredientIds: ["hyaluronic_acid"],
    fullIngredients: "Korean black rice extract 2,000ppm, hyaluronic acid 600ppm, beta-glucan, panthenol",
    origin: "South Korea",
    description: "A 95%-naturally-derived toner built around Korean black rice extract and hyaluronic acid for deep, plumping hydration — a favorite base step for a 'glass skin' routine.",
    usageSteps: [
      "Apply after cleansing",
      "Pat into skin with hands or a cotton pad",
      "Follow with serum/moisturizer",
    ],
    officialUrl: "https://haruharuusa.com",
    price: 22,
    currency: "USD",
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    concerns: ["hydration"],
  },
  {
    slug: "skin1004-madagascar-centella-ampoule",
    name: "Madagascar Centella Ampoule",
    brand: "SKIN1004",
    category: "essence",
    ingredientIds: ["centella"],
    fullIngredients: "Centella asiatica extract (Madagascar-grown, high madecassoside/TECA content), glycerin, butylene glycol",
    origin: "South Korea",
    description: "SKIN1004's hero product — a minimalist, fragrance-free centella ampoule formulated to soothe redness and reinforce the skin barrier for sensitive and irritated skin.",
    usageSteps: [
      "Apply after toner",
      "Pat 2-3 drops onto face and neck",
      "Follow with moisturizer",
    ],
    officialUrl: "https://www.skin1004.com",
    price: 17,
    currency: "USD",
    skinTypes: ["sensitive", "dry", "normal", "combination", "oily"],
    concerns: ["hydration", "redness", "barrier"],
  },
  {
    slug: "manyo-bifida-biome-complex-ampoule",
    name: "Bifida Biome Complex Ampoule",
    brand: "Ma:nyo",
    category: "essence",
    ingredientIds: ["niacinamide", "hyaluronic_acid", "peptides", "centella"],
    fullIngredients: "Bifida ferment lysate, 5-strain probiotic 'Bifida Biome' complex, 10 types of hyaluronic acid, niacinamide, acetyl hexapeptide-8, copper tripeptide-1, madecassic acid",
    origin: "South Korea",
    description: "A probiotic-fermented ampoule that pairs Ma:nyo's Bifida Biome complex with ten molecular weights of hyaluronic acid and peptides to rebuild a microbiome-friendly skin barrier.",
    usageSteps: [
      "Apply after toner, AM & PM",
      "Pat a few drops into skin",
      "Follow with moisturizer",
    ],
    price: 29,
    currency: "USD",
    skinTypes: ["dry", "sensitive", "normal", "combination"],
    concerns: ["barrier", "hydration", "aging"],
  },
  {
    slug: "neogen-dermalogy-real-ferment-micro-essence",
    name: "Dermalogy Real Ferment Micro Essence",
    brand: "Neogen",
    category: "essence",
    ingredientIds: ["niacinamide", "hyaluronic_acid"],
    fullIngredients: "93%+ fermented ingredients incl. bifida ferment lysate, saccharomyces (sake) ferment filtrate, birch juice, rice ferment filtrate, niacinamide, sodium hyaluronate",
    origin: "South Korea",
    description: "A fermentation-forward first essence inspired by sake brewing, combining bifida and saccharomyces ferment filtrates with birch juice to instantly plump and prep skin.",
    usageSteps: [
      "Apply after cleansing, AM & PM",
      "Pat or sweep onto face and neck",
      "Follow with serum/moisturizer",
    ],
    officialUrl: "https://neogenlab.us",
    price: 34,
    currency: "USD",
    skinTypes: ["normal", "dry", "combination", "oily"],
    concerns: ["hydration", "dullness"],
  },
  {
    slug: "innisfree-green-tea-seed-hyaluronic-serum",
    name: "Green Tea Seed Hyaluronic Serum",
    brand: "innisfree",
    category: "serum",
    ingredientIds: ["niacinamide", "hyaluronic_acid"],
    fullIngredients: "Jeju green tea leaf water, camellia sinensis seed oil, niacinamide, sodium hyaluronate, panthenol",
    origin: "South Korea",
    description: "Innisfree's best-selling serum, built on Jeju green tea and green tea seed oil, formulated with a 'Green Tea Tri-biotics' complex to hydrate and support the skin microbiome.",
    usageSteps: [
      "Apply after toner",
      "Press a few drops onto face and neck",
      "Follow with moisturizer",
    ],
    officialUrl: "https://us.innisfree.com",
    price: 34,
    currency: "USD",
    skinTypes: ["dry", "normal", "combination", "oily"],
    concerns: ["hydration", "dullness"],
  },
  {
    slug: "numbuzin-no3-skin-softening-serum",
    name: "No.3 Skin Softening Serum",
    brand: "numbuzin",
    category: "serum",
    ingredientIds: ["niacinamide", "hyaluronic_acid"],
    fullIngredients: "Bifida ferment lysate 42%, galactomyces ferment filtrate 21%, niacinamide, sodium hyaluronate, adenosine, panthenol",
    origin: "South Korea",
    description: "A fermented, texture-smoothing serum blending bifida and galactomyces ferments with niacinamide to visibly refine pores and soften rough skin texture.",
    usageSteps: [
      "Apply after toner, AM & PM",
      "Pat a few drops into skin",
      "Follow with moisturizer",
    ],
    officialUrl: "https://us.numbuzin.com",
    price: 26,
    currency: "USD",
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["pores", "dullness", "hydration"],
  },
  {
    slug: "kravebeauty-great-barrier-relief",
    name: "Great Barrier Relief",
    brand: "KraveBeauty",
    category: "serum",
    ingredientIds: ["niacinamide", "ceramides"],
    fullIngredients: "Ceramide NP, niacinamide, tamanu oil, beta-glucan, madecassoside",
    origin: "USA",
    description: "A reparative, fragrance-free serum built around ceramide NP and niacinamide to restore a compromised moisture barrier — developed by esthetician Liah Yoo for dry and sensitized skin.",
    usageSteps: [
      "Apply after toner/essence",
      "Massage a few drops into face and neck",
      "Follow with moisturizer to seal in",
    ],
    officialUrl: "https://kravebeauty.com",
    price: 32,
    currency: "USD",
    skinTypes: ["dry", "sensitive", "normal"],
    concerns: ["barrier", "hydration", "redness"],
  },
  {
    slug: "naturium-niacinamide-serum-12-zinc-2",
    name: "Niacinamide Serum 12% Plus Zinc 2%",
    brand: "Naturium",
    category: "serum",
    ingredientIds: ["niacinamide", "hyaluronic_acid", "vitamin_e"],
    fullIngredients: "Niacinamide 12%, zinc PCA 2%, sodium hyaluronate, tocopheryl acetate (vitamin E)",
    origin: "USA",
    description: "A high-strength niacinamide and zinc PCA serum aimed at oil control, visibly refined pores, and fading dark spots — one of Naturium's flagship, best-selling formulas.",
    usageSteps: [
      "Apply after cleansing/toning, AM or PM",
      "Apply a few drops to face",
      "Follow with moisturizer/SPF",
    ],
    officialUrl: "https://naturium.com",
    price: 16,
    currency: "USD",
    skinTypes: ["oily", "combination"],
    concerns: ["pores", "acne", "pigmentation"],
  },
  {
    slug: "peace-out-salicylic-acid-acne-healing-dots",
    name: "Salicylic Acid Acne Healing Dots",
    brand: "Peace Out Skincare",
    category: "spot",
    ingredientIds: ["bha", "retinol"],
    fullIngredients: "Salicylic acid 0.5%, retinyl acetate (vitamin A), aloe barbadensis leaf extract, hydrocolloid patch",
    origin: "USA",
    description: "A hydrocolloid pimple patch infused with salicylic acid and a retinoid derivative, clinically tested to visibly reduce blemishes in hours while shielding them from picking.",
    usageSteps: [
      "Apply to a clean, dry blemish",
      "Choose the dot size that fully covers the spot",
      "Leave on for several hours or overnight, then replace",
    ],
    officialUrl: "https://peaceoutskincare.com",
    price: 18,
    currency: "USD",
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["acne", "pores"],
  },
  {
    slug: "hero-cosmetics-mighty-patch-original",
    name: "Mighty Patch Original",
    brand: "Hero Cosmetics",
    category: "spot",
    ingredientIds: [],
    fullIngredients: "Medical-grade hydrocolloid (no active drug ingredients)",
    origin: "USA",
    description: "The viral, best-selling hydrocolloid acne patch — absorbs fluid from whiteheads overnight and shields blemishes from picking, with no active drug ingredients.",
    usageSteps: [
      "Apply to a clean, dry blemish that has come to a head",
      "Leave on for at least 6 hours or overnight",
      "Peel off once it turns white/opaque",
    ],
    officialUrl: "https://www.herocosmetics.us",
    price: 12,
    currency: "USD",
    skinTypes: ["oily", "combination", "normal", "sensitive"],
    concerns: ["acne"],
  },
  {
    slug: "glow-recipe-avocado-melt-retinol-eye-sleeping-mask",
    name: "Avocado Melt Retinol Eye Sleeping Mask",
    brand: "Glow Recipe",
    category: "eye",
    ingredientIds: ["retinol", "niacinamide", "hyaluronic_acid"],
    fullIngredients: "Encapsulated retinol, avocado oil and fruit extract, niacinamide, sodium hyaluronate, coffeeberry (coffea arabica fruit) extract",
    origin: "USA",
    description: "An overnight eye treatment that pairs encapsulated, slow-release retinol with avocado oil and niacinamide to smooth fine lines and depuff while you sleep.",
    usageSteps: [
      "PM only, as the last step",
      "Dot a small amount around the orbital bone",
      "Gently pat in — avoid direct contact with eyes",
    ],
    officialUrl: "https://www.glowrecipe.com",
    price: 39,
    currency: "USD",
    skinTypes: ["normal", "dry", "combination"],
    concerns: ["aging", "hydration"],
  },
  {
    slug: "first-aid-beauty-eye-duty-triple-remedy-am-gel-cream",
    name: "Eye Duty Triple Remedy AM Gel Cream",
    brand: "First Aid Beauty",
    category: "eye",
    ingredientIds: ["peptides", "hyaluronic_acid", "vitamin_e"],
    fullIngredients: "Palmitoyl hexapeptide-12, palmitoyl tetrapeptide-7, sodium hyaluronate, adenosine, tocopheryl acetate",
    origin: "USA",
    description: "A fast-absorbing peptide gel-cream for the eye area that targets puffiness and fine lines with a lightweight, makeup-friendly finish for daytime wear.",
    usageSteps: [
      "Apply AM as the last step before SPF",
      "Dot gently around the orbital bone",
      "Pat in until absorbed",
    ],
    officialUrl: "https://www.firstaidbeauty.com",
    price: 30,
    currency: "USD",
    skinTypes: ["normal", "dry", "combination", "sensitive"],
    concerns: ["aging", "hydration"],
  },
  {
    slug: "then-i-met-you-snail-mucin-eye-cream",
    name: "Snail Mucin Eye Cream",
    brand: "Then I Met You",
    category: "eye",
    ingredientIds: ["niacinamide", "peptides", "hyaluronic_acid"],
    fullIngredients: "Snail secretion filtrate, niacinamide, acetyl tetrapeptide-5, hyaluronic acid, caffeine, Volufiline",
    origin: "South Korea",
    description: "A firming, brightening eye cream from Charlotte Cho's Then I Met You, combining snail mucin with Volufiline and a de-puffing peptide to target dark circles, puffiness, and fine lines.",
    usageSteps: [
      "Apply AM and/or PM as the last step",
      "Dot around the orbital bone with ring finger",
      "Gently pat in until absorbed",
    ],
    officialUrl: "https://thenimetyou.com",
    price: 36,
    currency: "USD",
    skinTypes: ["normal", "dry", "combination"],
    concerns: ["aging", "hydration", "pigmentation"],
  },
  {
    slug: "etude-house-soonjung-2x-barrier-intensive-cream",
    name: "SoonJung 2X Barrier Intensive Cream",
    brand: "Etude House",
    category: "moisturizer",
    ingredientIds: ["centella"],
    fullIngredients: "Panthenol, madecassoside, sunflower seed oil, shea butter, camellia sinensis (green tea) leaf extract",
    origin: "South Korea",
    description: "A 92%-natural-origin barrier cream built around panthenol and madecassoside to repair and calm compromised, redness-prone skin.",
    usageSteps: [
      "Scoop a pea-sized amount",
      "Massage in as the final leave-on layer",
      "Use AM and/or PM",
    ],
    officialUrl: "https://www.etudehouse.com",
    price: 23,
    currency: "USD",
    skinTypes: ["sensitive", "dry", "normal"],
    concerns: ["barrier", "redness", "hydration"],
  },
  {
    slug: "dr-g-red-blemish-clear-soothing-cream",
    name: "R.E.D Blemish Clear Soothing Cream",
    brand: "Dr.G",
    category: "moisturizer",
    ingredientIds: ["niacinamide", "centella"],
    fullIngredients: "Niacinamide, centella asiatica extract, madecassoside, panthenol, beta-glucan, epigallocatechin gallate",
    origin: "South Korea",
    description: "A dermatologist-developed calming cream that soothes visible redness before and after breakouts while niacinamide helps even tone — a favorite for sensitive, blemish-prone skin.",
    usageSteps: [
      "Apply as the final leave-on step, AM/PM",
      "Take an appropriate amount and spread evenly",
      "Massage in gently",
    ],
    price: 30,
    currency: "USD",
    skinTypes: ["sensitive", "oily", "combination"],
    concerns: ["redness", "acne", "barrier"],
  },
  {
    slug: "vanicream-daily-facial-moisturizer",
    name: "Daily Facial Moisturizer with Hyaluronic Acid and Ceramides",
    brand: "Vanicream",
    category: "moisturizer",
    ingredientIds: ["ceramides", "hyaluronic_acid"],
    fullIngredients: "Squalane, hyaluronic acid, a 5-ceramide complex (ceramide NP, EOP, NG, AS, AP), phytosterols",
    origin: "USA",
    description: "A fragrance-free, dye-free moisturizer formulated without common irritants, combining a five-ceramide complex with hyaluronic acid to support the skin barrier for very sensitive skin.",
    usageSteps: [
      "Apply to clean skin, AM and/or PM",
      "Massage in until absorbed",
    ],
    officialUrl: "https://www.vanicream.com",
    price: 15,
    currency: "USD",
    skinTypes: ["dry", "sensitive", "normal"],
    concerns: ["barrier", "hydration"],
  },
  {
    slug: "kiehls-midnight-recovery-concentrate",
    name: "Midnight Recovery Concentrate",
    brand: "Kiehl's",
    category: "oil",
    ingredientIds: ["vitamin_e"],
    fullIngredients: "Squalane, evening primrose oil, lavender oil, rosehip seed oil (rosa canina fruit oil), tocopherol (vitamin E)",
    origin: "USA",
    description: "Kiehl's iconic overnight facial oil blend of botanical and essential oils, including evening primrose and lavender, formulated to restore radiance and support the skin barrier overnight.",
    usageSteps: [
      "Final PM step",
      "Warm 2-3 drops between palms",
      "Press gently over face and neck",
    ],
    officialUrl: "https://www.kiehls.com",
    price: 54,
    currency: "USD",
    skinTypes: ["dry", "normal", "combination"],
    concerns: ["aging", "dullness", "hydration"],
  },
  {
    slug: "skin1004-madagascar-centella-tone-brightening-tone-up-sunscreen",
    name: "Madagascar Centella Tone Brightening Tone-Up Sunscreen SPF50+ PA++++",
    brand: "SKIN1004",
    category: "sunscreen",
    ingredientIds: ["spf", "niacinamide", "centella"],
    fullIngredients: "Titanium dioxide, centella asiatica extract 29,400ppm, niacinamide, tranexamic acid, chemical + mineral UV filter blend",
    origin: "South Korea",
    description: "A hybrid mineral-chemical sunscreen with a soft tone-up finish, combining a high concentration of centella with niacinamide and tranexamic acid to brighten while protecting.",
    usageSteps: [
      "Apply as the last AM step",
      "Use generously, about two finger-lengths",
      "Reapply every 2 hours in the sun",
    ],
    officialUrl: "https://www.skin1004.com",
    price: 18,
    currency: "USD",
    skinTypes: ["oily", "dry", "combination", "normal", "sensitive"],
    concerns: ["redness", "pigmentation"],
  },
  {
    slug: "tatcha-silken-pore-perfecting-sunscreen-spf-35",
    name: "Silken Pore Perfecting Sunscreen SPF 35",
    brand: "Tatcha",
    category: "sunscreen",
    ingredientIds: ["spf"],
    fullIngredients: "Zinc oxide 15%, octisalate 5%, Japanese wild rose (rosa multiflora) extract, loquat leaf extract, silk extract",
    origin: "USA",
    description: "A lightweight, silicone-based mineral-chemical hybrid sunscreen that leaves a matte, pore-blurring finish — a favorite for oily and combination skin wanting SPF without shine.",
    usageSteps: [
      "Apply as the last AM step",
      "Smooth evenly over face and neck",
      "Reapply every 2 hours in the sun",
    ],
    officialUrl: "https://www.tatcha.com",
    price: 48,
    currency: "USD",
    skinTypes: ["oily", "combination", "normal"],
    concerns: ["pores"],
  },
  {
    slug: "eucerin-sun-gel-creme-oil-control-spf50",
    name: "Sun Gel-Creme Oil Control SPF 50+",
    brand: "Eucerin",
    category: "sunscreen",
    ingredientIds: ["spf"],
    fullIngredients: "Homosalate, octocrylene, butyl methoxydibenzoylmethane, ethylhexyl salicylate, licorice root (glycyrrhiza inflata) extract, glycyrrhetinic acid",
    origin: "Germany",
    description: "A dermocosmetic, oil-free chemical sunscreen with a matte, dry-touch finish designed specifically for oily and blemish-prone skin, from the German dermatology brand Eucerin.",
    usageSteps: [
      "Apply as the last AM step",
      "Smooth evenly over face",
      "Reapply every 2 hours in the sun",
    ],
    price: 19,
    currency: "USD",
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "pores"],
  },
];
