import type { SkinLesson } from './skin-lessons';

const care = 'https://www.aad.org/public/everyday-care/skin-care-basics/';
export const skinCourseFr: SkinLesson[] = [
  {
    id: 'skin', title: 'Reconnaître les besoins de sa peau',
    paragraphs: ['À la fin de ce chapitre, tu sauras distinguer un type de peau d’un état passager, observer chaque zone et choisir une première action sans acheter une routine entière.'],
    sections: [
      { title: 'Type, état et préoccupation : trois choses différentes', paragraphs: ['Le type décrit une tendance : une peau sèche produit généralement moins de sébum, une peau grasse en produit davantage, et une peau mixte présente des différences selon les zones. Une peau dite normale paraît globalement confortable. Ces catégories sont des repères, pas des cases immuables.', 'L’état décrit ce qui se passe maintenant : tiraillement, déshydratation, irritation. Une préoccupation est ce que tu souhaites améliorer : boutons, marques ou inconfort. Tu peux avoir une peau grasse, déshydratée et sensible en même temps. Un bouton ne suffit donc pas à conclure que toute ta peau est grasse.'] },
      { title: 'Observer sans provoquer une réaction', paragraphs: ['Pendant plusieurs jours, garde tes soins habituels bien tolérés. Note au réveil puis en fin de journée où ta peau brille, tire ou pèle. Regarde séparément le front, le nez, le menton et les joues. Il est inutile de laisser volontairement une peau inconfortable sans crème pour la « tester ».', 'Note aussi le contexte : chauffage, froid, nouveau nettoyant, rasage, transpiration ou traitement. Une seule journée atypique ne représente pas forcément ton fonctionnement habituel. La couleur de peau, l’âge ou une photo ne suffisent pas à déterminer le type de peau.'] },
      { title: 'Transformer une observation en un geste', paragraphs: ['Si les joues tirent mais que le nez brille, commence par une hydratation confortable et adapte la quantité selon la zone. Ne traite pas automatiquement les joues comme le nez. Si tout le visage tire après le nettoyage, questionne d’abord le nettoyant et la température de l’eau.', 'Une sensation de brûlure persistante, des démangeaisons ou une rougeur inhabituelle demandent de la prudence. Évite de multiplier les nouveautés pour corriger le problème. Un professionnel peut aider lorsque les symptômes durent, font mal ou s’aggravent.'] },
    ],
    example: 'Léa a le nez brillant et les joues qui tirent après un nettoyant moussant. Elle n’a pas besoin d’un soin matifiant partout : elle commence par un nettoyage plus doux et adapte son hydratant aux joues.',
    practice: ['Dessine mentalement quatre zones : front, nez, menton, joues.', 'Note le confort et la brillance de chaque zone pendant trois jours.', 'Choisis un seul besoin prioritaire : par exemple réduire le tiraillement.'],
    question: 'Ton nez brille, mais tes joues tirent. Quelle première démarche est la plus utile ?', answers: ['Décaper tout le visage', 'Observer chaque zone et adapter les soins', 'Supprimer toute hydratation'], correct: 1,
    explanation: 'Une brillance localisée ne décrit pas tout le visage. Une observation par zone permet d’ajuster la texture ou la quantité sans agresser les zones sèches.', source: 'https://www.aad.org/public/everyday-care/skin-care-basics/dry/pick-moisturizer',
  },
  {
    id: 'barrier', title: 'Comprendre la barrière cutanée', image: '/images/routine-sensitive-barrier.webp',
    paragraphs: ['La barrière cutanée aide la peau à retenir l’eau et à se protéger de son environnement. Ce chapitre explique pourquoi le confort passe souvent avant l’ajout d’un actif.'],
    sections: [
      { title: 'Ce que fait la couche externe de la peau', paragraphs: ['Imagine des cellules entourées de lipides : cet ensemble limite la perte d’eau. Le sébum est un film en surface ; ce n’est pas exactement la même chose que l’eau présente dans la peau. Une peau qui brille peut donc malgré tout tirer.', 'Le mot « barrière » sur un produit n’est pas une garantie de tolérance. Une formule entière, sa fréquence d’utilisation et les autres soins comptent davantage qu’un ingrédient mis en avant sur l’emballage.'] },
      { title: 'Nettoyer sans chercher la sensation qui crisse', paragraphs: ['Un nettoyage réussi retire les impuretés sans laisser une sensation de décapage. Utilise de l’eau tiède, les doigts et des gestes doux. Frotter plus fort ou multiplier les passages ne rend pas automatiquement la peau plus propre.', 'Un démaquillage suivi d’un nettoyant peut être pratique pour du maquillage ou des produits résistants, mais le double nettoyage n’est pas une obligation pour tout le monde. Si la peau tire, simplifier est parfois plus utile qu’ajouter une troisième étape.'] },
      { title: 'À quoi servent les textures hydratantes ?', paragraphs: ['Les humectants, comme la glycérine, attirent l’eau. Les émollients assouplissent la surface. Les ingrédients occlusifs limitent la perte d’eau. Une crème peut réunir plusieurs de ces fonctions : pas besoin d’un flacon pour chacune.', 'Choisis d’abord une texture confortable que tu utilises régulièrement. Une crème plus riche peut convenir aux zones sèches ; une texture légère peut être préférée sur les zones grasses. Si tu es réactif, les produits sans parfum peuvent être un point de départ, sans garantir une absence d’allergie.'] },
    ],
    example: 'Après une semaine de gommage quotidien, Sam sent sa crème habituelle piquer. Ajouter un exfoliant « plus doux » complique le problème. Il suspend les nouveautés irritantes et demande conseil si l’inconfort persiste.',
    practice: ['Observe le confort juste après ton nettoyage habituel.', 'Repère les exfoliants et gommages qui se répètent dans tes soins.', 'Garde une base simple bien tolérée avant toute nouveauté.'],
    question: 'Une peau très propre doit-elle forcément tirailler ?', answers: ['Oui, cela prouve que le sébum est parti', 'Non, le nettoyage peut rester confortable', 'Oui, surtout avant un sérum'], correct: 1,
    explanation: 'Le tiraillement n’est pas un objectif. Une sensation de décapage invite à revoir le nettoyage plutôt qu’à la rechercher.', source: care,
  },
  {
    id: 'routine', title: 'Construire le matin et le soir', image: '/images/routine-minimalist.webp',
    paragraphs: ['Le but est de comprendre le rôle de chaque étape, puis de conserver celles qui te servent. Un toner, une essence et trois sérums ne sont pas des passages obligés.'],
    sections: [
      { title: 'Le matin : préparer et protéger', paragraphs: ['Nettoie doucement si nécessaire, hydrate selon ton confort puis applique ta protection solaire. Si ton solaire est assez hydratant pour toi, une crème supplémentaire n’est pas toujours indispensable. Suis les indications de chaque produit.', 'Le solaire vient après les soins et avant le maquillage. Ne le mélange pas dans la main avec une crème pour gagner du temps : tu ne sais plus si le film protecteur est réparti comme prévu.'] },
      { title: 'Le soir : retirer et entretenir', paragraphs: ['Retire le maquillage et les produits de la journée avec un nettoyage adapté. Termine par un hydratant confortable. Un soin ciblé est une option pour un objectif précis, pas une obligation de chaque soir.', 'Si tu utilises un traitement prescrit, ses instructions priment sur un ordre générique. Pour les autres soins, aller des textures légères vers les crèmes est un repère pratique, pas une loi qui rendrait une formule inefficace au moindre écart.'] },
      { title: 'Savoir si une étape mérite sa place', paragraphs: ['Pour chaque produit, réponds à trois questions : quel est son rôle ? Est-ce que je le tolère ? Est-ce qu’un autre soin remplit déjà cette fonction ? Deux sérums proches ne donnent pas nécessairement deux fois plus de bénéfices.', 'Commence par une routine que tu peux suivre dans ton budget et ton emploi du temps. Si tu changes tout d’un coup, tu perds la possibilité de comprendre ce qui apporte du confort ou déclenche un problème.'] },
    ],
    example: 'Routine de départ : le matin, hydratation si besoin puis solaire ; le soir, nettoyage doux puis crème. Un sérum peut venir ensuite pour un besoin précis, une fois cette base confortable.',
    practice: ['Classe tes produits par fonction plutôt que par marque.', 'Écris ton matin et ton soir en trois lignes maximum pour commencer.', 'Repère une étape optionnelle que tu pourrais éviter de racheter.'],
    question: 'Deux sérums ont le même objectif. Que vérifier avant de les superposer ?', answers: ['Le nombre de produits conseillé sur les réseaux', 'Leur rôle, leur tolérance et leurs doublons', 'La couleur des flacons'], correct: 1,
    explanation: 'Le rôle et la tolérance permettent de juger l’utilité d’une étape. Le nombre de produits n’est pas un indicateur de qualité.', source: 'https://www.aad.org/public/everyday-care/skin-care-basics/care/skin-care-budget',
  },
  {
    id: 'actives', title: 'Introduire un actif sans tout changer', image: '/images/routine-brightening.webp',
    paragraphs: ['Un actif est un ingrédient choisi pour une fonction. Il faut regarder son usage dans la formule entière, pas simplement collectionner des noms ou rechercher le pourcentage le plus élevé.'],
    sections: [
      { title: 'Lire une promesse avec un objectif concret', paragraphs: ['Hydrater, exfolier et atténuer l’apparence des marques ne sont pas le même objectif. Choisis une priorité avant de comparer des sérums. Le nom d’un actif seul ne dit pas si une formule conviendra à ta peau.', 'Un pourcentage élevé n’est pas automatiquement préférable. La formule, la fréquence, la zone et les autres produits modifient la tolérance. La place d’un ingrédient dans une liste INCI ne permet pas d’en déduire précisément la concentration.'] },
      { title: 'Tester puis introduire progressivement', paragraphs: ['L’AAD décrit un essai local du produit pendant 7 à 10 jours, selon son mode d’emploi. Ce n’est pas un test allergologique médical et cela ne garantit pas l’absence de réaction future.', 'Introduis ensuite une seule nouveauté. Les actifs potentiellement irritants demandent une fréquence adaptée aux instructions et à ta tolérance. Ne commence pas plusieurs exfoliants et un rétinoïde dans la même semaine : tu ne saurais plus quoi ajuster.'] },
      { title: 'Réagir à un signal inconfortable', paragraphs: ['Brûler n’est pas une preuve que le soin fonctionne. Si une réaction apparaît, arrête le produit concerné et rince doucement si nécessaire. Demande conseil si la réaction est importante ou persiste.', 'N’appelle pas automatiquement « purge » tous les boutons apparus après une nouveauté. Une observation domestique ne permet pas toujours d’en identifier la cause. Pendant la grossesse ou l’allaitement, fais valider les produits ciblés par le professionnel qui te suit, notamment les rétinoïdes.'] },
    ],
    example: 'Mina ajoute un sérum le lundi puis un exfoliant le mercredi. Le vendredi, sa peau réagit : impossible de savoir lequel a contribué à la réaction. Une seule nouveauté à la fois rend le suivi plus lisible.',
    practice: ['Note la date de début, la fréquence et le produit.', 'Garde le reste de la routine stable autant que possible.', 'Consigne aussi les jours sans inconfort, pas seulement les réactions.'],
    question: 'Un produit brûle et laisse ta peau rouge. Quelle conclusion est correcte ?', answers: ['Il agit forcément en profondeur', 'Il faut en mettre davantage', 'Ce signal ne prouve pas son efficacité : arrête et demande conseil si nécessaire'], correct: 2,
    explanation: 'Une réaction ne mesure pas un bénéfice. La tolérance passe avant la recherche de résultats.', source: 'https://www.aad.org/public/everyday-care/skin-care-secrets/prevent-skin-problems/test-skin-care-products',
  },
  {
    id: 'sun', title: 'Utiliser sa protection solaire', image: '/images/routine-summer.webp',
    paragraphs: ['Ce chapitre t’aide à lire un solaire et à organiser sa réapplication. Un indice élevé ne transforme pas une seule application en protection illimitée.'],
    sections: [
      { title: 'SPF et large spectre', paragraphs: ['Le SPF renseigne principalement sur la protection contre les UV responsables des coups de soleil. La mention large spectre indique une protection UVA et UVB. L’AAD recommande un SPF 30 ou plus, à large spectre, avec une résistance à l’eau adaptée aux activités.', 'Choisis aussi une texture que tu supportes : elle facilite une application suffisante et régulière. La couleur de peau ne dispense pas de protection solaire.'] },
      { title: 'L’application compte autant que le flacon', paragraphs: ['Applique généreusement sur toutes les zones exposées selon l’étiquette, en pensant au cou et aux oreilles. Le solaire complète l’ombre et les vêtements ; il ne sert pas à prolonger sans limite le temps passé au soleil.', 'En extérieur, renouvelle environ toutes les deux heures et après baignade, transpiration ou essuyage, selon les instructions. Un produit résistant à l’eau n’est pas étanche pour la journée entière.'] },
      { title: 'Éviter les raccourcis trompeurs', paragraphs: ['Le SPF d’un maquillage ne garantit pas que la quantité de maquillage utilisée apporte la protection indiquée. Deux produits SPF 30 superposés ne font pas un SPF 60.', 'Si un solaire pique les yeux ou fait réagir ta peau, change de formule ou demande conseil. Retrouver une protection confortable est plus utile que forcer l’usage d’un produit mal toléré.'] },
    ],
    example: 'À la plage, un SPF 50 appliqué le matin ne dispense pas de réapplication après la baignade. Chapeau, vêtements et ombre réduisent aussi l’exposition.',
    practice: ['Vérifie SPF, large spectre et consignes de réapplication.', 'Repère les zones que tu oublies habituellement.', 'Prévois le produit et les protections physiques avant une sortie.'],
    question: 'Deux produits SPF 30 donnent-ils ensemble SPF 60 ?', answers: ['Oui, les indices s’additionnent', 'Non, les indices ne s’additionnent pas', 'Seulement si les marques diffèrent'], correct: 1,
    explanation: 'On ne peut pas additionner les indices. La quantité, l’uniformité du film et la réapplication restent essentielles.', source: 'https://www.aad.org/public/everyday-care/sun-protection/shade-clothing-sunscreen/choosing-right-sunscreen',
  },
  {
    id: 'observe', title: 'Suivre les changements sans se tromper', image: '/images/routine-winter.webp',
    paragraphs: ['Le suivi sert à décider quoi garder ou ajuster. Pour qu’il soit utile, il faut différencier ce que tu as observé de ce que tu peux réellement en conclure.'],
    sections: [
      { title: 'Partir d’une observation précise', paragraphs: ['« Ma peau est mieux » est difficile à comparer. « Mes joues tirent moins le soir » est plus précis. Choisis un objectif et note ta situation de départ, ta routine et la date du changement.', 'Un journal peut enregistrer les sensations, la fréquence réelle d’usage et les changements de contexte. Il ne prouve pas à lui seul qu’un produit cause un résultat.'] },
      { title: 'Rendre les comparaisons plus honnêtes', paragraphs: ['Pour les photos, garde autant que possible le même éclairage, le même angle et la même distance, sans filtre. Une lumière latérale accentue les reliefs ; une lumière plus diffuse peut les masquer. Cela peut donner une impression d’amélioration sans changement réel.', 'Une photo ne mesure pas directement ton confort ou l’eau contenue dans la peau. Combine ce qui est visible avec ton ressenti et les limites du résultat. Le scan aide à observer, il ne remplace pas un diagnostic.'] },
      { title: 'Savoir dire : je ne peux pas conclure', paragraphs: ['Si tu as changé plusieurs produits, manqué beaucoup d’utilisations ou pris des photos très différentes, indique-le. Quelques jours sans note ne sont ni des jours sans réaction ni des jours d’utilisation confirmée.', 'Le calendrier de suivi n’est pas une promesse de résultat. Au bilan, tu peux garder, ajuster, arrêter ou choisir « pas assez de recul ». Ce dernier choix évite une certitude inventée et garde une trace utile pour la prochaine décision.'] },
    ],
    example: 'Haru retrouve deux notes sur quatorze jours. Il peut afficher ces deux observations, mais ne doit pas présenter les douze jours restants comme douze jours de bonne tolérance.',
    practice: ['Choisis un changement et un objectif observables.', 'Note ce qui s’est réellement passé, même si le plan n’a pas été suivi.', 'Au bilan, sépare les faits, les hypothèses et les informations manquantes.'],
    question: 'Tu as deux notes en quatorze jours. Que peut-on dire des douze autres jours ?', answers: ['La peau allait forcément bien', 'Le produit a été utilisé chaque jour', 'Aucune observation n’a été enregistrée pour ces jours'], correct: 2,
    explanation: 'Une absence de note est une absence d’information. Ce n’est pas une preuve de tolérance ou d’utilisation.', source: care,
  },
];
