export type SkinLesson = { id: string; title: string; image: string; paragraphs: string[]; question: string; answers: string[]; correct: number; explanation: string; source: string };
const sources = {
  skin: "https://www.aad.org/public/everyday-care/skin-care-basics/dry/pick-moisturizer",
  routine: "https://www.aad.org/public/everyday-care/skin-care-basics/care/skin-care-budget",
  actives: "https://www.aad.org/public/everyday-care/skin-care-secrets/prevent-skin-problems/test-skin-care-products",
  sun: "https://www.aad.org/public/everyday-care/skin-care-secrets/routine/healthier-looking-skin",
};
const entries: Record<string, Omit<SkinLesson, "id" | "image" | "source">[]> = {
  fr: [
    { title:"Comprendre sa peau", paragraphs:["Observez les zones grasses, sèches et les sensations de tiraillement. Une peau mixte peut briller sur le front et le nez tout en étant sèche sur les joues.","Choisissez une texture hydratante adaptée : un gel est léger, une crème plus riche. La sensibilité peut accompagner différents types de peau ; évitez de conclure à partir d’une seule photo."], question:"Des joues sèches et une zone T grasse peuvent correspondre à…", answers:["Une peau mixte","Une peau qui n’a jamais besoin d’hydratation","Un diagnostic certain sur photo"], correct:0, explanation:"Différentes zones peuvent avoir des besoins différents. L’observation aide à choisir ses soins ; elle ne remplace pas un diagnostic." },
    { title:"Construire une routine simple", paragraphs:["La base : nettoyer doucement, hydrater et protéger du soleil. Multiplier les produits peut coûter plus cher et irriter la peau.","Le soir, nettoyez avant vos soins. Suivez les indications de chaque produit, notamment pour les traitements prescrits. Une routine courte que vous tolérez est un bon point de départ."], question:"Quel est le meilleur point de départ ?", answers:["Dix produits appliqués dès le premier soir","Nettoyage doux, hydratation et protection solaire","Un exfoliant à chaque étape"], correct:1, explanation:"Commencez par les fonctions essentielles. Ajoutez ensuite seulement ce qui répond à un besoin identifié." },
    { title:"Introduire un nouveau produit", paragraphs:["Avant de l’ajouter, testez le produit sur une petite zone selon ses instructions. L’AAD propose un essai local pendant 7 à 10 jours ; ce test ne garantit pas l’absence de réaction future.","Si une réaction apparaît, rincez doucement et arrêtez le produit. Une irritation sévère ou persistante mérite un avis médical. Ne cherchez pas à supporter une brûlure pour obtenir des résultats."], question:"Un nouveau soin provoque une réaction. Que faire ?", answers:["Augmenter la quantité","Continuer jusqu’à s’habituer","Arrêter le produit et demander conseil si nécessaire"], correct:2, explanation:"Une réaction n’est pas une preuve d’efficacité. Un test domestique ne remplace pas les tests allergologiques médicaux." },
    { title:"Comprendre la protection solaire", paragraphs:["Choisissez une protection à large spectre, SPF 30 minimum et résistante à l’eau. Complétez-la avec de l’ombre et des vêtements protecteurs.","Renouvelez l’application selon l’étiquette, notamment après baignade ou transpiration. Le SPF ne rend pas la peau invulnérable : la protection repose aussi sur vos habitudes."], question:"Une bonne protection combine…", answers:["SPF uniquement quand la peau rougit","Écran solaire adapté, ombre et vêtements","Une seule application pour toute la semaine"], correct:1, explanation:"L’écran solaire fait partie d’un ensemble de mesures de protection, même avec un SPF élevé." },
  ],
  en: [
    {title:"Understand your skin",paragraphs:["Notice oily areas, dry patches and tightness. Combination skin can be oily on the forehead and nose while the cheeks are dry.","Choose a moisturizer texture that suits your needs: a gel is light, while a cream is richer. Sensitivity can occur with different skin types; one photo cannot establish a diagnosis."],question:"Dry cheeks and an oily T-zone may indicate…",answers:["Combination skin","Skin that never needs moisturizer","A certain diagnosis from a photo"],correct:0,explanation:"Different areas can have different needs. Observation can guide your choices but is not a diagnosis."},
    {title:"Build a simple routine",paragraphs:["Start with gentle cleansing, moisturizing and sun protection. Adding more products can increase both cost and irritation.","Cleanse before your evening skin care. Follow each product’s directions, especially prescribed treatments. A short routine your skin tolerates is a useful starting point."],question:"What is a useful starting point?",answers:["Ten products on the first night","Gentle cleansing, moisturizer and sun protection","Exfoliation at every step"],correct:1,explanation:"Start with essential functions. Add products only for an identified need."},
    {title:"Introduce a new product",paragraphs:["Try a product on a small area first, following its directions. The AAD suggests a local test over 7 to 10 days; this cannot rule out every future reaction.","If a reaction occurs, gently wash the product off and stop using it. Seek medical advice for severe or persistent irritation. Burning is not something you need to endure for results."],question:"A new product causes a reaction. What should you do?",answers:["Increase the amount","Keep using it until you adapt","Stop and seek advice if needed"],correct:2,explanation:"A reaction is not proof that a product works. A home test does not replace medical allergy testing."},
    {title:"Understand sun protection",paragraphs:["Choose broad-spectrum, water-resistant SPF 30 or higher. Add shade and protective clothing.","Reapply as directed on the label, especially after swimming or sweating. SPF does not make skin invulnerable: your habits matter too."],question:"Good protection combines…",answers:["Sunscreen only after redness appears","Suitable sunscreen, shade and clothing","One application for the entire week"],correct:1,explanation:"Sunscreen is one part of sun protection, even when its SPF is high."},
  ],
  ko: [
    {title:"내 피부 이해하기",paragraphs:["유분이 많은 부위, 건조한 부위, 당기는 느낌을 살펴보세요. 복합성 피부는 이마와 코가 번들거리면서 볼은 건조할 수 있어요.","피부에 맞는 보습 제형을 고르세요. 젤은 가볍고 크림은 더 풍부합니다. 민감함은 여러 피부 타입에서 나타날 수 있으며, 사진 한 장만으로 진단할 수는 없어요."],question:"볼은 건조하고 T존은 번들거린다면?",answers:["복합성 피부일 수 있어요","보습이 전혀 필요 없어요","사진만으로 확실히 진단할 수 있어요"],correct:0,explanation:"부위마다 필요한 관리가 다를 수 있어요. 관찰은 제품 선택을 돕지만 진단을 대신하지는 않아요."},
    {title:"간단한 루틴 만들기",paragraphs:["기본은 순한 세안, 보습, 자외선 차단입니다. 제품을 많이 추가하면 비용과 자극이 늘 수 있어요.","저녁에는 세안 후 스킨케어를 하세요. 처방 제품을 포함해 각 제품의 사용 지침을 따르세요. 피부가 편안한 짧은 루틴부터 시작해 보세요."],question:"어떤 루틴으로 시작하면 좋을까요?",answers:["첫날부터 제품 열 개 사용","순한 세안, 보습, 자외선 차단","모든 단계마다 각질 제거"],correct:1,explanation:"필수 기능부터 갖추고, 필요한 목적이 있을 때 제품을 추가하세요."},
    {title:"새 제품 사용하기",paragraphs:["새 제품은 사용 지침에 따라 작은 부위에 먼저 시험해 보세요. AAD는 7~10일 동안 국소 테스트를 권하지만, 이후의 모든 반응을 예방할 수는 없어요.","반응이 생기면 부드럽게 씻어내고 사용을 중단하세요. 자극이 심하거나 지속되면 의료진과 상담하세요. 효과를 위해 화끈거림을 참을 필요는 없어요."],question:"새 제품에 피부 반응이 생겼다면?",answers:["사용량을 늘려요","적응할 때까지 계속 사용해요","중단하고 필요하면 상담해요"],correct:2,explanation:"피부 반응이 효과의 증거는 아니에요. 집에서 하는 테스트는 의료기관의 알레르기 검사를 대신하지 않아요."},
    {title:"자외선 차단 이해하기",paragraphs:["광범위 자외선 차단, SPF 30 이상, 내수성 제품을 선택하세요. 그늘과 피부를 가리는 옷도 함께 활용하세요.","제품 안내에 따라 덧바르고, 특히 수영이나 땀을 흘린 뒤에 신경 써 주세요. SPF가 높아도 피부가 완전히 보호되는 것은 아니에요."],question:"좋은 자외선 보호 방법은?",answers:["피부가 붉어진 뒤에만 차단제 사용","적절한 차단제, 그늘, 옷 함께 활용","일주일에 한 번만 바르기"],correct:1,explanation:"SPF가 높더라도 차단제는 여러 보호 방법 중 하나예요."},
  ],
  ja: [
    {title:"自分の肌を知る",paragraphs:["皮脂の多い部分、乾燥、つっぱり感を観察しましょう。混合肌では額や鼻が脂っぽく、頬が乾燥することがあります。","肌に合う保湿剤の質感を選びましょう。ジェルは軽く、クリームはより濃厚です。敏感さはさまざまな肌タイプに見られ、写真一枚では診断できません。"],question:"頬が乾燥し、Tゾーンが脂っぽい場合は？",answers:["混合肌の可能性がある","保湿が一切不要","写真だけで確実に診断できる"],correct:0,explanation:"部分ごとに必要なケアは異なります。観察は選択の助けになりますが、診断ではありません。"},
    {title:"シンプルなルーティン",paragraphs:["基本はやさしい洗顔、保湿、紫外線対策です。製品を増やすと費用や刺激が増えることがあります。","夜はスキンケアの前に洗顔を。処方薬を含め、各製品の使用方法を守りましょう。肌に合う短いルーティンから始めましょう。"],question:"最初にそろえる基本は？",answers:["初日から10製品を使う","やさしい洗顔・保湿・紫外線対策","毎ステップで角質ケア"],correct:1,explanation:"必要な機能から始め、明確な目的があるときに製品を追加しましょう。"},
    {title:"新しい製品を取り入れる",paragraphs:["使用方法に従い、まず小さな範囲で試しましょう。AADは7〜10日間の局所テストを提案していますが、将来のすべての反応を防げるわけではありません。","反応が出たらやさしく洗い流し、使用を中止しましょう。刺激が強い、または続く場合は医療機関に相談してください。効果のために灼熱感を我慢する必要はありません。"],question:"新しい製品で反応が出たら？",answers:["使用量を増やす","慣れるまで使い続ける","使用を中止し、必要に応じて相談"],correct:2,explanation:"反応は効果の証明ではありません。家庭でのテストは医療機関のアレルギー検査とは異なります。"},
    {title:"紫外線対策を知る",paragraphs:["広範囲の紫外線を防ぐ、耐水性のあるSPF30以上の日焼け止めを選びましょう。日陰や衣服も活用します。","表示に従って塗り直し、特に水泳や発汗後は注意しましょう。SPFが高くても完全な保護にはなりません。"],question:"適切な紫外線対策は？",answers:["赤くなってから日焼け止めを使う","日焼け止め・日陰・衣服を組み合わせる","週に一度だけ塗る"],correct:1,explanation:"高いSPFでも、日焼け止めは複数の対策の一つです。"},
  ],
};
const ids = ["skin", "routine", "actives", "sun"] as const;
const images = ["glow", "minimal", "brightening", "hydration"];
export function skinLessons(locale: string): SkinLesson[] {
  return (entries[locale] ?? entries.en).map((entry, index) => ({ ...entry, id: ids[index], source: sources[ids[index]], image: `/images/routine-${images[index]}.webp` }));
}
