"use client";

import { useMemo, useState } from "react";
import { ArrowUpRight, Check, ShoppingBag } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ProductImage } from "@/components/product-image";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Link } from "@/i18n/navigation";
import type { Product } from "@/generated/prisma/client";

const routines = [
  { key: "sensitive", title: "Barrière apaisée", skin: "Peau sensible ou déshydratée", note: "Quatre gestes doux pour hydrater sans multiplier les actifs.", slugs: ["round-lab-birch-juice-moisturizing-cleanser", "cosrx-advanced-snail-96-mucin-power-essence", "skin1004-madagascar-centella-ampoule", "beauty-of-joseon-relief-sun"] },
  { key: "oily", title: "Pores & brillance", skin: "Peau grasse ou mixte", note: "Une base courte, avec l&apos;exfoliation réservée à quelques soirs par semaine.", slugs: ["cosrx-low-ph-good-morning-gel-cleanser", "round-lab-1025-dokdo-toner", "cosrx-bha-blackhead-power-liquid", "round-lab-birch-juice-moisturizing-sun-cream-spf50"] },
  { key: "glow", title: "Éclat & taches", skin: "Peau terne ou marques visibles", note: "Des actifs éclat, puis une protection solaire indispensable le matin.", slugs: ["beauty-of-joseon-green-plum-refreshing-toner", "round-lab-vita-niacinamide-dark-spot-serum", "beauty-of-joseon-glow-serum-propolis-niacinamide", "beauty-of-joseon-relief-sun"] },
];

export function KBeautyRoutineBuilder({ products }: { products: Product[] }) {
  const [active, setActive] = useState("sensitive");
  const routine = routines.find((item) => item.key === active) ?? routines[0];
  const selected = useMemo(() => routine.slugs.map((slug) => products.find((product) => product.slug === slug)).filter((product): product is Product => Boolean(product)), [products, routine]);
  return <section className="bg-[#080707] py-20 sm:py-28"><div className="mx-auto max-w-6xl px-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div className="max-w-2xl"><p className="text-sm font-medium text-primary">Routines K-beauty</p><h2 className="mt-3 text-balance text-3xl font-semibold tracking-tight sm:text-5xl">Compose une routine complète, sans te perdre.</h2><p className="mt-4 leading-7 text-muted-foreground">Des sélections simples à adapter à ton passeport de peau. Clique sur un produit pour l&apos;usage, l&apos;origine et les liens officiels.</p></div><Button asChild variant="outline" className="shrink-0 rounded-full"><Link href="/app/routine">Adapter à ma routine <ArrowUpRight className="size-4" /></Link></Button></div><div className="mt-8 flex gap-2 overflow-x-auto pb-2">{routines.map((item) => <button key={item.key} onClick={() => setActive(item.key)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-medium transition ${active === item.key ? "bg-primary text-primary-foreground" : "bg-white/[0.07] text-foreground hover:bg-secondary"}`}>{item.skin}</button>)}</div><div className="mt-8 flex items-center justify-between gap-6"><div><p className="text-sm text-muted-foreground">Routine sélectionnée</p><h3 className="mt-1 text-2xl font-semibold sm:text-3xl">{routine.title}</h3></div><p className="hidden max-w-md text-right text-sm leading-6 text-muted-foreground md:block">{routine.note.replace("&apos;", "'")}</p></div><div className="no-scrollbar mt-5 flex gap-5 overflow-x-auto pb-4">{selected.map((product, index) => <RoutineProduct key={product.id} product={product} step={index + 1} />)}</div><div className="mt-4 flex items-start gap-2 text-sm leading-6 text-muted-foreground"><Check className="mt-0.5 size-4 shrink-0 text-primary" />Ne démarre pas tous les actifs d&apos;un coup : introduis-les progressivement.</div></div></section>;
}

function RoutineProduct({ product, step }: { product: Product; step: number }) {
  return <Dialog><DialogTrigger asChild><button className="haru-home-product-card w-44 shrink-0 overflow-hidden text-left transition hover:-translate-y-1 sm:w-48"><ProductImage imageUrl={product.imageUrl} category={product.category} name={product.name} size="lg" /><span className="block px-3 py-2"><span className="text-[10px] font-medium text-primary">Étape {step}</span><span className="mt-0.5 block truncate text-sm font-semibold">{product.name}</span><span className="mt-0.5 block truncate text-xs text-muted-foreground">{product.brand} · {product.category}</span></span></button></DialogTrigger><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>{product.name}</DialogTitle><DialogDescription>{product.brand} · Fabriqué en {product.origin}</DialogDescription></DialogHeader><p className="text-sm leading-6 text-muted-foreground">{product.description}</p><div><p className="text-sm font-semibold">Conseils d&apos;utilisation</p><ul className="mt-2 grid gap-2 text-sm text-muted-foreground">{product.usageSteps.map((step) => <li key={step}>• {step}</li>)}</ul></div><div className="flex flex-wrap gap-2"><Button asChild><Link href={`/app/product/${product.slug}`}>Fiche & ingrédients</Link></Button><Button asChild variant="outline"><Link href="/app/routine">Ajouter à ma routine</Link></Button>{product.officialUrl && <Button asChild variant="ghost"><a href={product.officialUrl} target="_blank" rel="noreferrer"><ShoppingBag className="size-4" /> Avis & achat</a></Button>}</div></DialogContent></Dialog>;
}
