import Image from 'next/image';
import { getLocale } from 'next-intl/server';
import { ScanFace, ArrowUpRight, ClipboardCheck, BookOpen } from 'lucide-react';
import { Link } from '@/i18n/navigation';

const copies = {
  fr: { title:'Scanner ma peau', text:'Un point de départ pour comprendre les signes visibles sur ton visage et préparer tes prochains gestes.', cta:'Commencer mon scan visage', note:'Photo choisie par toi · compte requis · analyse cosmétique, sans diagnostic', preview:'Aperçu du parcours · portrait illustratif', steps:[['Observer','Une photo dans de bonnes conditions, avec les limites de l’analyse.'],['Comprendre','Des observations expliquées, à compléter par ton ressenti.'],['Décider','Croise le scan avec tes produits et ton audit de routine.']], lab:'Que s’est-il passé depuis mon dernier changement ?', labText:'Le suivi de routine récapitule tes observations et les jours sans note. Tu peux choisir « pas assez de recul » et retrouver tes bilans précédents.', labCta:'Ouvrir mon suivi', learn:'Comprendre le suivi' },
  en: {title:'Scan my skin',text:'A starting point to understand visible facial features and plan your next steps.',cta:'Start my face scan',note:'You choose the photo · account required · cosmetic analysis, not a diagnosis',preview:'Journey preview · illustrative portrait',steps:[['Observe','A photo in suitable conditions, with analysis limitations.'],['Understand','Explained observations, complemented by how your skin feels.'],['Decide','Review the scan alongside your products and routine audit.']],lab:'What happened since my last change?',labText:'Routine tracking summarizes recorded observations and days without notes. Choose “Not enough information” and revisit previous decisions.',labCta:'Open my tracking',learn:'Learn about tracking'},
  ko: {title:'내 피부 스캔하기',text:'얼굴에서 보이는 특징을 이해하고 다음 케어를 준비해 보세요.',cta:'얼굴 스캔 시작',note:'직접 선택하는 사진 · 로그인 필요 · 진단이 아닌 미용 분석',preview:'이용 과정 미리보기 · 예시 인물',steps:[['관찰','적절한 조건의 사진과 분석의 한계를 확인해요.'],['이해','관찰 내용을 피부의 실제 느낌과 함께 살펴요.'],['선택','제품과 루틴 점검 결과를 함께 확인해요.']],lab:'지난 변경 이후 무엇을 기록했나요?',labText:'루틴 기록에서 관찰 내용과 기록이 없는 날을 구분해요. 정보가 부족하면 결론을 보류하고 이전 기록도 확인할 수 있어요.',labCta:'내 기록 열기',learn:'피부 관리 배우기'},
  ja: {title:'肌をスキャン',text:'顔に見える特徴を理解し、次のケアを考えるきっかけに。',cta:'顔スキャンを始める',note:'自分で写真を選択 · ログインが必要 · 診断ではなく美容分析',preview:'利用の流れ · イメージ画像',steps:[['観察','適切な条件で撮影し、分析の限界も確認。'],['理解','観察結果と実際の肌の感覚を組み合わせる。'],['選択','製品やルーティンチェックと一緒に見直す。']],lab:'前の変更から何を記録した？',labText:'観察記録と記録のない日を区別します。情報不足なら結論を保留し、過去の記録も確認できます。',labCta:'記録を開く',learn:'ケアを学ぶ'},
};
export async function SkinScannerShowcase() {
  const locale = await getLocale();
  const t = copies[locale as keyof typeof copies] ?? copies.en;
  return <section id="skin-scanner" className="haru-learning mx-auto max-w-7xl scroll-mt-24 px-5 py-10 sm:px-8" aria-labelledby="scanner-title">
    <div className="grid overflow-hidden rounded-[32px] border border-border bg-white/80 lg:grid-cols-[.8fr_1.2fr]">
      <div className="relative min-h-64 bg-secondary sm:min-h-80"><Image src="/images/routine-glow.webp" alt="" fill sizes="(min-width:1024px) 40vw, 100vw" className="object-cover" /><div className="absolute inset-8 rounded-[40%] border border-white/80" aria-hidden="true" /><span className="absolute bottom-4 left-4 right-4 rounded-xl bg-white/90 px-3 py-2 text-xs leading-5">{t.preview}</span></div>
      <div className="min-w-0 p-6 sm:p-10"><ScanFace className="mb-4 size-8" aria-hidden="true"/><h2 id="scanner-title">{t.title}</h2><p className="mt-4 max-w-lg text-base leading-7 text-muted-foreground">{t.text}</p><ol className="my-6 space-y-4">{t.steps.map(([title,text],i)=><li key={title} className="flex gap-3"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-secondary text-xs">{i+1}</span><div><p className="font-semibold">{title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></li>)}</ol><Link href="/app/face-scan" className="haru-cta">{t.cta}<ArrowUpRight className="size-4" /></Link><p className="mt-3 text-xs leading-5 text-muted-foreground">{t.note}</p></div>
    </div>
    <div className="mt-5 flex flex-col gap-5 rounded-3xl bg-secondary/60 p-6 sm:p-8 lg:flex-row lg:items-center"><ClipboardCheck className="size-7 shrink-0"/><div className="min-w-0 flex-1"><h3>{t.lab}</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{t.labText}</p></div><div className="flex shrink-0 flex-col gap-3"><Link href="/app/shelf" className="haru-cta">{t.labCta}</Link><Link href="/learn#observe" className="inline-flex items-center justify-center gap-2 text-sm underline underline-offset-4"><BookOpen className="size-4"/>{t.learn}</Link></div></div>
  </section>;
}
